---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/centos7-java
    tag: "latest"

outputs:
- name: built-app

inputs:
- name: pipeline-repo
- name: application

run:
  path: pipeline-repo/ci/scripts/build.sh
