---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/alpine-cf-cli
    tag: "latest"

inputs:
- name: bins
- name: pipeline-repo

outputs:
- name: outputs 

run:
  path: pipeline-repo/ci/scripts/deploy.sh
  args: [ f1 ] 

