---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/headless-chrome
    tag: "latest"

run:
  path: pipeline-repo/ci/scripts/end-to-end-test.sh
  args: [ f2 ]

inputs:
- name: pipeline-repo
