---
platform: linux

image_resource:
  type: docker-image
  source:
    repository:   agf234/headless-chrome
    tag: "latest"

inputs:
- name: pipeline-repo
- name: dd

run:
  path: pipeline-repo/ci/scripts/end-to-end-test.sh
  args: [ f1 ]
