---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/centos7-java
    tag: "latest"

inputs:
- name: pipeline-repo
- name: bins

run:
  path: pipeline-repo/ci/scripts/unit-test-app.sh
