---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos
    tag: "7"

run:
  path: sh
  args: 
  - -exc
  - |
    export TERM=vt100
    echo "starting to run pipeline!"

inputs:
- name: pipeline-repo
- name: application

